platform :ios, '9.0'

target 'ClimateProgrammatically' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ClimateProgrammatically
  
  pod 'SwiftyJSON'
  pod 'Alamofire'
  pod 'SVProgressHUD'

end
